CREATE DATABASE QLTV;

USE QLTV;

CREATE TABLE `ADMIN`(
	ID_ADMIN INT NOT NULL AUTO_INCREMENT,
    NAMETAG NVARCHAR(20) NOT NULL,
    `PASSWORD` NVARCHAR(20) NOT NULL,
    CONSTRAINT PK_ADMIN PRIMARY KEY (ID_ADMIN)
);

CREATE TABLE CUSTOMER(
	ID_CUSTOMER INT NOT NULL AUTO_INCREMENT,
    NAME_CUSTOMER NVARCHAR(50) NOT NULL,
    BIRTHDAY DATE,
    ADDRESS NVARCHAR(200),
    PHONE NVARCHAR(11),
    EMAIL NVARCHAR(100),
     CONSTRAINT PK_CUSTOMER PRIMARY KEY (ID_CUSTOMER)
    
);

CREATE TABLE CATEGORY(
	ID_CATEGORY INT NOT NULL AUTO_INCREMENT,
    NAME_CATEGORY  NVARCHAR(50) NOT NULL,
    CONSTRAINT PK_CATEGORY PRIMARY KEY(ID_CATEGORY)
);

CREATE TABLE ARTHOR(
	ID_ARTHOR INT NOT NULL AUTO_INCREMENT,
	NAME_AUTHOR NVARCHAR(50),
    CONSTRAINT PK_ARTHOR PRIMARY KEY(ID_ARTHOR)
);

CREATE TABLE PUBLISHER(
	ID_PUBLISHER INT NOT NULL AUTO_INCREMENT,
	NAME_PUBLISHER NVARCHAR(100),
    CONSTRAINT PK_ARTHOR PRIMARY KEY(ID_PUBLISHER)
);

CREATE TABLE BOOK(
	ID_BOOK INT NOT NULL AUTO_INCREMENT,
    NAME_BOOK NVARCHAR(50) NOT NULL,
    ID_CATEGORY INT NOT NULL,
    ID_ARTHOR INT NOT NULL,
    ID_PUBLISHER INT NOT NULL,
    CONSTRAINT PK_BOOK PRIMARY KEY(ID_BOOK),
    CONSTRAINT FK_BOOK_CATEGORY FOREIGN KEY(ID_CATEGORY) REFERENCES CATEGORY(ID_CATEGORY),
    CONSTRAINT FK_BOOK_ARTHOR FOREIGN KEY(ID_ARTHOR) REFERENCES ARTHOR(ID_ARTHOR),
    CONSTRAINT FK_BOOK_PUBLISHER FOREIGN KEY(ID_PUBLISHER) REFERENCES PUBLISHER(ID_PUBLISHER)
);

CREATE TABLE BILL(
	ID_BILL INT NOT NULL AUTO_INCREMENT,
    ID_ADMIN INT NOT NULL,
    ID_CUSTOMER INT NOT NULL,
    CREATED_DATE DATE,
    CONSTRAINT PK_BILL PRIMARY KEY(ID_BILL),
    CONSTRAINT FK_BILL_ADMIN FOREIGN KEY (ID_ADMIN) REFERENCES `ADMIN`(ID_ADMIN),
    CONSTRAINT FK_BILL_CUSTOMER FOREIGN KEY(ID_CUSTOMER) REFERENCES CUSTOMER(ID_CUSTOMER)
);

CREATE TABLE BILL_DETAIL(
	ID_BOOK INT NOT NULL,
    ID_BILL INT NOT NULL,
    AMOUNT INT,
    PRICE FLOAT,
    CONSTRAINT FK_BILL_DETAIL_BOOK FOREIGN KEY(ID_BOOK) REFERENCES BOOK(ID_BOOK),
    CONSTRAINT FK_BILL_DETAIL_BILL FOREIGN KEY (ID_BILL) REFERENCES BILL(ID_BILL)
);



